vich_uploader:
  db_driver: orm

  mappings:
    curriculum_vitae:
      uri_prefix: /uploads/cv
      upload_destination: '%kernel.project_dir%/public/uploads/cv'

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
